import type { Metadata } from "next";

import "./globals.css";
import { Providers } from "./Component/Providers/Providers";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "ShopeEase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
